import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Example from '../components/Home/Example'
import How from '../components/Home/How/How'
import Splash from '../components/Home/Splash'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Splash />
      <How />
      <Example />      
    </div>
  )
}

export default Home
